### ISSUE TITLE
Размещение в скрытом контейнере

### ISSUE THREAD

**Issue by 7iomka** [R1ZEN/react-yandex-maps#26]
Доброго времени суток.
https://codesandbox.io/s/dank-fast-se8fej?file=/src/App.tsx

Кейс: на сайте в футере есть картинка со скрином карты и кнопка открывающая модалку с картой (в портале).
Подскажите как доработать код чтобы
- карта получала актуальные значения контейнера после открытия модалки
  (гуглил, в нативном коде нужно делать что-то типо `myMap.container.fitToViewport();` но в реакте не знаю как этот флоу описать
  
- скрипт апи карты в первый раз грузился (если не загружен) перед открытием модалки (если читать вашу доку скрипт начинает грузится когда во вьюпорте карта появляется, в случае с модалкой это должно как-то аналогичным образом хендлиться)

**Comment by 7iomka** [comment]
Разобрался.
https://codesandbox.io/s/silly-sutherland-4nmz2y

**Comment by R1ZEN** [comment]
@7iomka доступность можно отследить через callback в instanceRef, `instanceRef={(ref) => setYmapsInstance(ref)}` и в useEffect завязываться на установленное значение
