### ISSUE TITLE
Access Map instance with `withYMaps` hook

### ISSUE THREAD

**Issue by Semro** [R1ZEN/react-yandex-maps#30]
Hello!
Is it possible to get map instance through `withYMaps` hook that was created in other component with `useYMaps`?

**Comment by R1ZEN** [comment]
@Semro Hello! No, you can't access to the instance of map through hook `useYMaps`.  To access a map instance use `instanceRef` prop on Map component.

**Comment by Semro** [comment]
I see. Thank you!
