### ISSUE TITLE
Добавить поддержку отрисовки кастомных контролов

### ISSUE THREAD

**Issue by palych063** [R1ZEN/react-yandex-maps#43]
Добрый день, есть ли возможность добавлять кастомные контролы по типу таких?
https://yandex.ru/dev/maps/jsbox/2.1/custom_control

**Comment by R1ZEN** [comment]
@palych063 добрый день, компонента под кастомные контролы нет) но можно получить ymaps из хука `useYMaps` и использовать как в примере
