### ISSUE TITLE
Для FullscreenControl не хватает типизации

### ISSUE THREAD

**Issue by HappyFeedFriends** [R1ZEN/react-yandex-maps#50]
В поле `data` не хватает ` image`, `context` поля по типам.

Дока яндекса: https://yandex.com/dev/maps/jsapi/doc/2.1/ref/reference/control.FullscreenControl.html#control.FullscreenControl__param-parameters.state

Типы у пакета:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/31066449/218379246-14239df1-eb10-4865-a028-f324f4f6fc9b.png">

В рантайме всё работает отлично

**Comment by R1ZEN** [comment]
Привет) Типа нет в библиотеке типов для yandex карт: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yandex-maps/index.d.ts#L446
Лучше им создать issue)
