### ISSUE TITLE
Подскажите как реализовать редирект по клику на элемент балуна.

### ISSUE THREAD

**Issue by JohnGlod** [R1ZEN/react-yandex-maps#56]
У меня есть метка, хочу сделать, чтобы по клику на элемент балуна (к примеру image), происходил редирект по нужному адресу. Но не могу сообразить, как привязать адекватно колбек.
![image](https://user-images.githubusercontent.com/78054338/222515682-47d85047-380a-4a39-95ce-9d55cfef8bc8.png)

**Comment by Wimmind** [comment]
@JohnGlod у него есть пропс onClick

**Comment by JohnGlod** [comment]
> @JohnGlod у него есть пропс onClick
У балуна или у самой метки? Не вижу подобного пропа, да и в их интерфейсе такого нет.

**Comment by tilvan** [comment]
@JohnGlod у самого Placemark
```
<Placemark ... onClick={(event) => { ... }} />
```
