### ISSUE TITLE
Некорректно отображаются метки при динамическом изменении набора объектов

### ISSUE THREAD

**Issue by tilvan** [R1ZEN/react-yandex-maps#57]
При использовании `geoObject` и при динамическом изменении набора объектов некоторые метки не отображаются на карте, хотя находятся в инстансе `geoObject`-а.

Закинул пример в репозиторий
https://github.com/tilvan/yandex-map-example
Для воспроизведения нужно покликать кнопку сверху.
На карте должна оставаться одна метка.
Центр карты смещается как надо, но сама метка не отображается до тех пор, пока не изменю зум карты туда-сюда.

**Comment by EfimShikanov** [comment]
@tilvan привет! Удалось решить проблему? Если удалось, то в чем заключалось решение?

**Comment by tilvan** [comment]
@EfimShikanov нет, не удалось
