### ISSUE TITLE
Night Mode react/javascript

### ISSUE THREAD

**Issue by KalyDanil** [R1ZEN/react-yandex-maps#61]
Подскажите, пожалуйста, как включить темную тему для react/javascript? В официальной документации яндекс карт описывается такая возможность только для yandex map kit.

**Comment by Semro** [comment]
https://ru.stackoverflow.com/questions/1505723/%d0%9a%d0%b0%d0%ba-%d0%bf%d0%b5%d1%80%d0%b5%d0%ba%d0%bb%d1%8e%d1%87%d0%b8%d1%82%d1%8c-%d0%af%d0%bd%d0%b4%d0%b5%d0%ba%d1%81-%d0%9a%d0%b0%d1%80%d1%82%d1%8b-%d0%b2-%d0%bd%d0%be%d1%87%d0%bd%d0%be%d0%b9-%d1%80%d0%b5%d0%b6%d0%b8%d0%bc/1505727#1505727
