### ISSUE TITLE
Defaultprops deprecated

### ISSUE THREAD

**Issue by master4o** [R1ZEN/react-yandex-maps#67]
Warning: Unknown: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

Стоит ли ждать обновления?)

**Comment by R3flector** [comment]
Joining the question, this warning in the console log is irritating to the eye

**Comment by shimprog** [comment]
Кто-нибудь нашел элегантное решение данной проблемы? )

**Comment by master4o** [comment]
По всей видимости просто легче создать свою обертку и настроить, как нужно, обращаясь ко встроенным методам напрямую. 

https://yandex.ru/dev/jsapi30/doc/ru/dg/concepts/general#react

**Comment by R3flector** [comment]
Up!
