### ISSUE TITLE
Отключение информации от Яндекса при клике на объект

### ISSUE THREAD

**Issue by IlyaLisov** [R1ZEN/react-yandex-maps#77]
Есть ли какая-нибудь возможность отключить balloon после клика пользователем по Яндекс объекту на карте?

То есть, чтобы при клике на название сквера ничего не происходило. Пока это работает, если не указывать `apikey`, однако он мне нужен.

![image](https://github.com/R1ZEN/react-yandex-maps/assets/69322277/4606f8ef-7648-4d8c-9980-72ab36c6ed4c)

**Comment by anyabravich** [comment]
yandexMapDisablePoiInteractivity: true,

**Comment by IlyaLisov** [comment]
@anakolchina97 спасибо большое, почему-то не заметил сразу!
